name: school
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  localstorage: ^2.0.0
  unicorndial: ^1.1.5
  fluttertoast: ^3.1.0
  material_design_icons_flutter: ^3.2.3895
  oktoast: ^2.2.0
  toast: ^0.1.5
  sms: ^0.2.4
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  sqflite: ^1.1.6+3
  path_provider: ^1.2.0
  flutter_slidable: ^0.5.3
  shared_preferences: ^0.5.3+4
  permission_handler: ^3.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^1.6.0+2
  build_runner: any
  flutter_launcher_icons: ^0.7.2+1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  image_path: "icon/iconlogo.png"
  android: true
  ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - images/icon-01.png
    - images/icon-02.png
    - images/icon-03.png
    - images/icon-04.png
    - images/icon-05.png
    - images/icon-06.png
    - images/icon-07.png
    - images/icon-08.png
    - images/icon-09.png
    - images/icon-10.png
    - images/icon-11.png
    - images/icon-12.png
    - images/icon-13.png
    - images/icon-14.png
    - images/icon-15.png
    - images/icon-16.png
    - images/icon-17.png
    - images/icon-18.png
    - images/icon-19.png
    - images/icon-20.png
    - images/icon-21.png
    - images/icon-22.png
    - images/icon-23.png
    - images/icon-24.png
    - images/icon-25.png
    - images/icon-26.png
    - assets/locale/localization_en.json
    - assets/locale/localization_kh.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
